name: basic_shared_element_transition
description: An example showing how to create a simple shared element (or Hero) transition.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/flippers-alpha.png
