container:
  image: gcr.io/flutter-cirrus/build-website-image:latest

website_task:
  env:
    CIRRUS_WORKING_DIR: "/opt/website"
    # For deploying master website to Firebase master branch site
    FIREBASE_TOKEN: ENCRYPTED[882ce80b2cc441774c7c4ca4aa861cca2581b70e88cfe0b6cb94094f40ff424f335888eec191ca71379652056d760231]
  git_fetch_script: git fetch origin
  setup_script: ./tool/setup.sh
  pub_cache:
    folder: "$PUB_CACHE"
    fingerprint_script: echo $OS && find "$CIRRUS_WORKING_DIR" -type f -name pubspec.yaml -print0 | xargs -0 sha256sum
  test_script: ./tool/build_check_deploy.sh

docker_builder:
  # Only build a new docker image when we tag a release. Can also be run manually.
  only_if: $CIRRUS_TAG != ''
  env:
    GCLOUD_CREDENTIALS: ENCRYPTED[f7c098d4dd7f5ee1bfee0bb7e944cce72efbe10e97ad6440ae72de4de6a1c24d23f421a2619c668e94377fb64b0bb3e6]
  depends_on:
    - website
  build_script: "$CIRRUS_WORKING_DIR/tool/docker/docker_build.sh"
  login_script: "$CIRRUS_WORKING_DIR/tool/docker/docker_login.sh"
  push_script: "$CIRRUS_WORKING_DIR/tool/docker/docker_push.sh"
