container:
  image: gcr.io/flutter-cirrus/build-website-image:latest

website_task:
  # Only run this one on PR builds.
  only_if: $CIRRUS_PR != ''
  env:
    CIRRUS_WORKING_DIR: "/opt/website"
  git_fetch_script: git fetch origin
  setup_script: ./tool/setup.sh
  pub_cache:
    folder: "$PUB_CACHE"
    fingerprint_script: echo $OS && find "$CIRRUS_WORKING_DIR" -type f -name pubspec.yaml -print0 | xargs -0 sha256sum
  test_script: ./tool/build_check_deploy.sh

deploy_website_task:
  # Only run this one for non-PR builds on master branch to protect the secret.
  only_if: $CIRRUS_BRANCH == 'master' && $CIRRUS_PR == ''
  env:
    CIRRUS_WORKING_DIR: "/opt/website"
    # For deploying master website to Firebase master branch site
    FIREBASE_TOKEN: ENCRYPTED[e207f0b4fb77024c6a2d9f43b25c6a0d04b1e9f6ea77f50904d815a82062ad62043303ade58a2cab809848435799b01c]
  git_fetch_script: git fetch origin
  setup_script: ./tool/setup.sh
  pub_cache:
    folder: "$PUB_CACHE"
    fingerprint_script: echo $OS && find "$CIRRUS_WORKING_DIR" -type f -name pubspec.yaml -print0 | xargs -0 sha256sum
  test_script: ./tool/build_check_deploy.sh

docker_builder:
  # Only build a new docker image when we tag a release, and not on a PR. Can also be run manually.
  only_if: $CIRRUS_TAG != '' && $CIRRUS_PR == ''
  env:
    GCLOUD_CREDENTIALS: ENCRYPTED[f7c098d4dd7f5ee1bfee0bb7e944cce72efbe10e97ad6440ae72de4de6a1c24d23f421a2619c668e94377fb64b0bb3e6]
  depends_on:
    - website
  build_script: "$CIRRUS_WORKING_DIR/tool/docker/docker_build.sh"
  login_script: "$CIRRUS_WORKING_DIR/tool/docker/docker_login.sh"
  push_script: "$CIRRUS_WORKING_DIR/tool/docker/docker_push.sh"
