# Site settings
title: Flutter
email: sky-dev@googlegroups.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://flutter.github.io"
github_username:  flutter

# Build settings
markdown: kramdown
