# Site settings
title: Flutter
# description: TBC
email: flutter-dev@googlegroups.com
url: https://flutter.io
port: 4002
github_username: flutter
repo:
  this: https://github.com/flutter/website
  flutter: https://github.com/flutter/flutter
branch: dash # TODO: reset to master

pub: https://pub.dartlang.org

defaults:
- scope:
    path: ''
  values:
    layout: default

# Build settings
source: src
# `symlinked-sources` can refer to individual files or directories
# under `src` that are symlinked to somewhere outside `src`, or it can
# refer to the root folder of the symlinked content (like `site-shared/src`):
symlinked-sources: [site-shared/src]

plugins:
  - jekyll-redirect-from # TODO(chalin): drop this in favor of Firebase redirects

## Site-wide shorthands

alert:
  tip: >-
    <aside class="alert alert-success" role="alert" markdown="1">
    <i class="fa fa-lightbulb-o"></i> **Tip:**
  note: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="fa fa-info-circle"></i> **Note:**
  important: >-
    <aside class="alert alert-warning" role="alert">
    <i class="fa fa-warning"></i> **Important:**
  warning: >-
    <aside class="alert alert-danger" role="alert">
    <i class="fa fa-exclamation-circle"></i> **Warning:**
  end: </aside>

  # callout_danger: '<div class="bs-callout bs-callout-danger">'
  # callout_default: '<div class="bs-callout bs-callout-default">'
  # callout_primary: '<div class="bs-callout bs-callout-primary">'
  # callout_success: '<div class="bs-callout bs-callout-success">'
  # callout_info: '<div class="bs-callout bs-callout-info">'
  # callout_warning: '<div class="bs-callout bs-callout-warning">'

  # hr_faded: '<hr class="faded"/>'
  # hr_shaded: '<hr class="shaded"/>'

codelab-code-url: https://raw.githubusercontent.com/chalin/flutter-codelabs/master
