name: basic_hero_dialog
description: An example showing how to create a shared element (or Hero) transition within the same page.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/backpack-alpha.png
