name: add_language
description: An i18n app example that adds a supported language

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any # Take the version from Flutter.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
